name: laravel_echo
description: Port of official Laravel Echo package for your Flutter apps.
version: 2.0.0
homepage: https://github.com/vfiruz97/echo

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
